// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"shengcai/internal/handler"
	"shengcai/internal/repository"
	"shengcai/internal/server"
	"shengcai/internal/service"
	"shengcai/pkg/app"
	"shengcai/pkg/jwt"
	"shengcai/pkg/log"
	"shengcai/pkg/server/http"
	"shengcai/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db, viperViper)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT, viperViper)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	sheetInfoRepository := repository.NewSheetInfoRepository(repositoryRepository)
	aiRepository := repository.NewAIRepository(repositoryRepository)
	cellDataRepository := repository.NewCellDataRepository(repositoryRepository, aiRepository)
	feiShuService := service.NewFeiShuService(serviceService, sheetInfoRepository, cellDataRepository)
	shengCaiService := service.NewShengCaiService(serviceService, feiShuService, cellDataRepository)
	shengCaiHandler := handler.NewShengCaiHandler(handlerHandler, shengCaiService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, shengCaiHandler)
	job := server.NewJob(logger, shengCaiService, aiRepository)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewShengCaiRepository, repository.NewSheetInfoRepository, repository.NewCellDataRepository, repository.NewAIRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewFeiShuService, service.NewShengCaiService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewShengCaiHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
